### ISSUE TITLE
Failed to activate the img-placeholder package

### ISSUE THREAD

**Issue by ghost** [maxxcrawford/img-placeholder#5]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [img-placeholder](https://github.com/maxxcrawford/img-placeholder) package, v0.7.0
### Stack Trace

Failed to activate the img-placeholder package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
  at __extends (/Users/mimmvo/.atom/packages/img-placeholder/lib/img-placeholder-view.coffee:1:1)
  at /Users/mimmvo/.atom/packages/img-placeholder/lib/img-placeholder-view.coffee:5:3
  at Object.<anonymous> (/Users/mimmvo/.atom/packages/img-placeholder/lib/img-placeholder-view.coffee:52:5)
  at Object.<anonymous> (/Users/mimmvo/.atom/packages/img-placeholder/lib/img-placeholder-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/mimmvo/.atom/packages/img-placeholder/lib/img-placeholder.coffee:1:22)
  at Object.<anonymous> (/Users/mimmvo/.atom/packages/img-placeholder/lib/img-placeholder.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:709:34)
  at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:257:12)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:236:14)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:772:25
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:222:20)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:156:19)
  at [object Object].jQuery.fn.trigger (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:64:23)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:75:67)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:169:7)
  at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:150:33)
  at HTMLDocument.handler (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)

```
### Commands

```
     -1:59.5.0 pane:reopen-closed-item (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-atom-dark-ui)
     -0:36.2.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:34.3.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:34.3.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:34.3.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "disabledPackages": [
      ".bin",
      "aligner"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
aligner-css, v1.2.0
angularjs, v0.3.0
ascii-codes, v0.3.3
atom-alignment, v0.12.1
atom-beautify, vundefined
atom-html-preview, v0.1.8
atom-lorempixel, v0.1.0
atom-python-debugger, v0.3.4
atom-ternjs, v0.6.7
atom-typescript, v4.8.1
auto-detect-indentation, v0.4.2
auto-indent, v0.5.0
autoclose-html, v0.18.0
autocomplete-modules, v1.0.0
autocomplete-plus-python-jedi, v0.3.6
autocomplete-python, v0.5.1
color-picker, v2.0.7
css-color-underline, v1.0.1
css-snippets, v0.8.0
ctags-status, v1.3.2
drop-up, v0.1.2
editorconfig, v1.0.1
ember-snippets, v1.3.0
emmet, v2.3.11
highlight-column, v0.5.0
highlight-line, v0.11.0
highlight-selected, v0.10.1
html-id-class-snippets, v1.4.1
img-placeholder, v0.7.0
indent-guide-improved, v1.4.0
inline-autocomplete, v1.1.0
javascript-snippets, v1.0.0
jshint, v1.3.8
language-javascript-better, v1.5.0
language-javascript-semantic, v0.2.1
language-python-django-templates, v0.1.0
linter, v1.1.0
minimap, v4.10.1
minimap-color-highlight, v4.1.4
minimap-highlight-selected, v4.3.0
minimap-pigments, v0.1.1
monokai, v0.14.0
open-recent, v2.2.4
pigments, v0.8.2
processing-language, v0.2.0
project-colorize, v0.2.0
script-runner, v1.8.3
simple-drag-drop-text, v0.2.3
terminal-status, v1.6.8
trailing-spaces, v0.3.2
webbox-color, v0.5.7

# Dev
No dev packages
```

**Comment by maxxcrawford** [comment]
Looks like this issue is related to updating packages. See below from @izuzak 

> This should show up only after you update some packages. If you restart Atom after that everything should be fine. We're tracking this problem over in [#416](https://github.com/atom/settings-view/issues/416) so I'm going to close this. Thanks for the report, though!

Please let me know if you have any further issues!
